@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" PersonList

PersonList -right-> "*" Person

Person *--> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Company
Person *--> HomeCountry
@enduml
